// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingMachine.Service.Orders.Data;

namespace VendingMachine.Service.Orders.Data.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20200130080107_FirstMigrationOrders")]
    partial class FirstMigrationOrders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VendingMachine.Service.Orders.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VendingMachine.Service.Orders.Domain.Order", b =>
                {
                    b.OwnsOne("VendingMachine.Service.Orders.Domain.MachineStatus", "MachineStatus", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("CoinsCurrentSupply")
                                .HasColumnName("CoinsCurrentSupply")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("MachineId")
                                .HasColumnName("MachineId")
                                .HasColumnType("int");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("VendingMachine.Service.Orders.Domain.OrderProductItem", "OrderProductItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<int>("ProductItemId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderProductItem");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("VendingMachine.Service.Orders.Domain.GrossPrice", "Price", b2 =>
                                {
                                    b2.Property<int>("OrderProductItemId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<decimal>("NetPrice")
                                        .HasColumnName("NetPrice")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("Rate")
                                        .HasColumnName("Rate")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<int>("TaxPercentage")
                                        .HasColumnName("TaxPercentage")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Value")
                                        .HasColumnName("GrossPrice")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("OrderProductItemId");

                                    b2.ToTable("OrderProductItem");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderProductItemId");
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
